---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.application_name | quote }}
    template: generic-java-buildconfig
  name: {{ .Values.application_name | quote }}